name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print hola mundo
        run: echo "hola mundo"
      - name: print chao
        run: echo "chao"
      

        
 
